---
- name: Check namespace doesn't already exist
  shell: oc get namespace {{ mobile_services_namespace }}
  register: namespace_exists
  failed_when: namespace_exists.stderr != '' and 'NotFound' not in namespace_exists.stderr

- name: Creating namespace {{ mobile_services_namespace }}
  shell: oc new-project {{ mobile_services_namespace }}
  when: namespace_exists.rc != 0