---
- name: Install mdc resources
  shell: "oc apply -f {{ item }} -n {{ mobile_services_namespace }}"
  with_items: "{{ mdc_resources }}"

- set_fact:
    mdc_openshift_host: "{{ openshift_master_url }}"
  when: mdc_openshift_host is undefined

- name: Process operator template
  template:
    src: operator.yml.j2
    dest: "/tmp/mdc-operator.yml"

- name: Provision mdc operator
  shell: "oc apply -f /tmp/mdc-operator.yml -n {{ mobile_services_namespace }}"

- name: Delete mdc operator temporary file
  file:
    path: /tmp/mdc-operator
    state: absent

- name: Get deployment desired replicas
  shell: "oc get deployment/mobile-developer-console-operator -o jsonpath='{.spec.replicas}' -n {{ mobile_services_namespace }}"
  register: mdc_operator_replicas_cmd

- name: Wait for operator readiness
  shell: "oc get deployment/mobile-developer-console-operator -o jsonpath='{.status.availableReplicas}' -n {{ mobile_services_namespace }}"
  register: result
  until: result.stdout == mdc_operator_replicas_cmd.stdout
  retries: 50
  delay: 10
  failed_when: result.stderr
  changed_when: False
