---
- name: Process mdc template
  template:
    src: mobiledeveloperconsole.yml.j2
    dest: "/tmp/mobiledeveloperconsole.yml"

- name: Apply mdc resource
  shell: "oc apply -f /tmp/mobiledeveloperconsole.yml -n {{ mobile_services_namespace }}"

- name: Delete mdc template file
  file:
    path: /tmp/mobiledeveloperconsole.yml
    state: absent

- name: Wait for mdc readiness
  shell: "oc get mobiledeveloperconsole/{{ mdc_name }} -o jsonpath='{.status.phase}' -n {{ mobile_services_namespace }}"
  register: result
  until: result.stdout == 'Complete'
  retries: 50
  delay: 10
  failed_when: result.stderr
  changed_when: False