mobile_security_service_name: "mobile-security-service"
mobile_security_service_operator_resources: 'https://raw.githubusercontent.com/aerogear/mobile-security-service-operator/{{mss_operator}}/deploy'
mobile_security_service_operator_image: 'quay.io/aerogear/mobile-security-service-operator:{{mss_operator}}'

mobile_security_service_operator_resource_items:
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityserviceapp_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/crds/mobile-security-service_v1alpha1_mobilesecurityservicebackup_crd.yaml"
  - "{{ mobile_security_service_operator_resources }}/cluster_role.yaml"
  - "{{ mobile_security_service_operator_resources }}/service_account.yaml"
