---

- name: Install Mobile Services to an OpenShift cluster
  hosts: localhost
  roles:
  - role: namespace
  - role: pull-secrets
  - role: idm
  - role: ups
  vars_files:
  - ./versions.yml 
  - ./variables.yml