---
- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: mdc
        tasks_from: cors.yml

    - name: restart openshift master services
      shell: "/usr/local/bin/master-restart {{ item }}"
      become: yes
      with_items:
        - api
        - controllers

    - name: check if openshift master services are running
      shell: oc get nodes
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 5
      failed_when: task_result.rc != 0
  vars_files:
  - variables.yml