---
mdc_operator_resources: 'https://raw.githubusercontent.com/aerogear/mobile-developer-console-operator/{{mdc_operator}}/deploy'
mdc_name: mdc
mdc_oauth_client_id: mobile-developer-console
mdc_resources:
  - "{{ mdc_operator_resources }}/service_account.yaml"
  - "{{ mdc_operator_resources }}/role.yaml"
  - "{{ mdc_operator_resources }}/role_binding.yaml"
  - "{{ mdc_operator_resources }}/crds/mdc_v1alpha1_mobiledeveloperconsole_crd.yaml"
  - "{{ mdc_operator_resources }}/mobileclient_admin_role.yaml"
  - "{{ mdc_operator_resources }}/mdc_v1alpha1_mobileclient_crd.yaml"
  - "{{ mdc_operator_resources }}/mobiledeveloper_role.yaml"
  - "{{ mdc_operator_resources }}/mobiledeveloper_rolebinding.yaml"
mdc_openshift_master_config_path: "/etc/origin/master/master-config.yaml"

mdc_operator_image: 'quay.io/aerogear/mobile-developer-console-operator:{{mdc_operator}}'
mdc_image: 'quay.io/aerogear/mobile-developer-console:{{mdc}}'
mdc_proxy_image: 'quay.io/openshift/origin-oauth-proxy:{{mdc_proxy}}'

documentation_url: https://docs.aerogear.org/limited-availability/downstream

ups_documentation_url: "{{ documentation_url }}/ups.html"
idm_documentation_url: "{{ documentation_url }}/idm.html"
sync_documentation_url: "{{ documentation_url }}/sync.html"
mss_documentation_url: "{{ documentation_url }}/mss.html"
