---

namespace: "{{ mobile_services_namespace }}"
appname: showcase1
push_android_sender_id: ""
push_android_server_key: ""
push_ios_cert_content: ""
push_ios_cert_passphase: ""
push_ios_cert_production: ""
datasync_server:
  - datasync
showcase_server_file_storage_size: 100Mi