---

- name: Copy ServiceBinding template {{ item }}
  template:
    src: "{{ item }}.json.j2"
    dest: "/tmp/{{ item }}.json"

- name: Create ServiceBinding instance {{ item }}
  shell: oc apply -f /tmp/{{ item }}.json -n {{ mobile_services_namespace }}

- name: Remove temporary file
  file:
    path: "/tmp/{{ item }}.json"
    state: absent